name: Resume RAG Chatbot CI/CD

on:

  push:
    branches:
      - main


jobs:

  build-and-test:

    runs-on: ubuntu-latest


    steps:

      # ==============================
      # Checkout Repo
      # ==============================

      - name: Checkout Repository
        uses: actions/checkout@v4


      # ==============================
      # Python Setup
      # ==============================

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      # ==============================
      # Install Backend Dependencies
      # ==============================

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt


      # ==============================
      # Node Setup
      # ==============================

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"


      # ==============================
      # Install Frontend Dependencies
      # ==============================

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install


      # ==============================
      # Docker Build Test
      # ==============================

      - name: Build Docker Containers
        run: |
          docker compose build
